name: download_file
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=24.0
  - requests=2.32.3
  - mlflow=2.19.0
  - scikit-learn=1.6.1
  - pip:
    - wandb==0.19.4
    - git+https://github.com/udacity/nd0821-c2-build-model-workflow-starter.git#egg=wandb-utils&subdirectory=components
